baseurl = "http://skyportsystems.com"
languageCode = "en-us"
title = "Skyport Systems"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false

[indexes]
  tag = "tags"
