baseurl = "http://rexk.github.io/skyportsystems.github.io"
languageCode = "en-us"
title = "Skyports Systems"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false

[indexes]
  tag = "tags"
